#!/bin/bash
# make sure we switch back to ro on shutdown
systemctl enable --runtime microos-ro.service
systemctl mask --runtime transactional-update.service
mount -o remount,rw /
btrfs prop set -t s / ro false
cat <<EOF
##########################
# Root FS switches to RW #
# Operating out of spec, #
#       be careful!      #
##########################
EOF
