#!/bin/bash
set -euxo pipefail
exec &>/dev/ttyS0
# Poweroff immediately on any failure to avoid unnecessary waiting.
trap '[ $? -eq 0 ] || poweroff -f' EXIT

# Remove old microos-tools
rpm -e --nodeps --noscripts --nodb microos-tools
# Install microos-tools
mount -t 9p -o trans=virtio tmpdir /mnt
chown -R root:root /mnt/install/usr
cp -av /mnt/install/usr /
umount /mnt

# Make sure that the system comes up good, leave a marker in the shared FS
# and power off the VM.
cat >>/usr/bin/combustion-validate <<'EOF'
#!/bin/bash
set -euxo pipefail
trap '[ $? -eq 0 ] || poweroff -f' EXIT
# Print a list of files which have SELinux label mismatches
if restorecon -nvR -e /.snapshots -e /run / | grep -v wtmpdb | grep "Would relabel"; then
	echo "Some labels aren't correct?"
	exit 1
fi
mount -t 9p -o trans=virtio tmpdir /mnt
touch /mnt/done
umount /mnt
poweroff -f
EOF
chmod a+x /usr/bin/combustion-validate

cat >>/etc/systemd/system/combustion-validate.service <<'EOF'
[Service]
Type=oneshot
StandardOutput=journal+console
ExecStart=/usr/bin/combustion-validate
[Install]
RequiredBy=default.target
EOF
systemctl enable combustion-validate.service
